### ISSUE TITLE
DFS_recursive_inorder_btree in Julia would crash for singe-branch tree 

### ISSUE THREAD

**Issue by jiegillet** [algorithm-archivists/algorithm-archive#110]
In the code below, I think the case of single branch binary trees was not considered. It is checking >2 and >0 but not ==1 yet it uses [1]. We should add a case for single branch (which I realize is not well defined for here since we don't know if it's a left or right branch).

https://github.com/algorithm-archivists/algorithm-archive/blob/d9d8405e9f31a0de82e8dcdfdb42b12978779ec3/chapters/tree_traversal/code/julia/Tree.jl#L28-L43

**Comment by leios** [comment]
Yeah, I see what you are saying. We might want to rework this section so that the children are not a vector of child nodes, but instead left and right branches, which are more standard for binary trees anyway.

The reason I went with this implementation to begin with is because we defined node earlier in the chapter, but we could define a `binary_node` for the binary tree cases and go with that too.

**Comment by jiegillet** [comment]
I think it's OK to go with that implementation for now since it's used throughout the chapter and in order is just a special case quickly covered. Just add the case length(n.children) == 1 with a comment saying "for simplicity we assume it's a left branch" or something.

**Comment by leios** [comment]
Yeah. I think that's probably fine in this case, but I know several people have wanted me to split the chapter into two anyway, so maybe this is a good chance to do so?

**Comment by jiegillet** [comment]
Yeah, why not. Maybe talk a bit about binary search trees or something to flesh it out.

**Comment by jiegillet** [comment]
Fixed in #172
