### ISSUE TITLE
Problem with Git

### ISSUE THREAD

**Issue by johhnry** [algorithm-archivists/algorithm-archive#153]
Hey guys,

I'm a beginner with Git and I red this tutorial : https://github.com/johhnry/algorithm-archive/blob/master/chapters/principles_of_code/version_control.md

I succeeded installing git and cloning the algorithm-archive repository localy.

But it seems really confusing to me, I have an error with the command : 

`git push remote master`

```
fatal: remote does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

I would like to submit algorithms in C / Python and Processing to help the community.

Thanks in advance

Joseph

**Comment by lulucca12** [comment]
` git remote set-url origin https://github.com/algorithm-archivists/algorithm-archive.git`

**Comment by Butt4cak3** [comment]
You probably wanted to run `git push origin master`. "origin" is the name of a so-called remote.

If you want and that's your thing, you can join our Discord (linked in the README on the front page of this repo) and we can try to figure everything out there. That might be a bit easier than here.

**Comment by johhnry** [comment]
Thanks for your answers @lulucca12 and @Butt4cak3 

- @lulucca12 I don't really understand your answer, cloud you provide more informations?
- @Butt4cak3 Git language is very confuse and it's not very clear for me (more because I'm french). I don't know if I will use Discord... Anyway is there a simplier way to contribute ?

Thanks

Joseph

**Comment by Butt4cak3** [comment]
GitHub is definitely the best way to contribute, because wen can use it to review and include the code easily. If you can't use Git for whatever reason, you could probably send it @leios' way by other means like E-Mail or something similar.

**Comment by leios** [comment]
Yeah, if you are having trouble with git, please ask our community for help (even on discord: https://discord.gg/2kWgSWB). I used to allow code submissions via e-mail, twitter, youtube comment... etc.; however, it is frankly not possible to review the code submitted in this way. 

We understand that git is difficult for newbies and we are doing what we can to make it easier.

**Comment by leios** [comment]
Hey @johhnry , were you able to figure out the git issues? If so, could you tell us what helped you understand it in the end? We are working on improving our *How to Contribute* chapter and such.

**Comment by johhnry** [comment]
Hey @leios 

Sorry for answering late and thanks for being reactive.
I think I'll try another time to understand Git in details (specially I'll try to watch tutorials in french).
I let you know if I am able or not to overcome Git issues.

Thanks

**Comment by johhnry** [comment]
I just have a question : 

If I want to contribute and write code in Processing language (which is a Java based language), in which format do I need to put it?
Is someone ever submitted a code in Processing, do I have to create a new folder in the code folder like "python", "c" or "julia" ?

**Comment by Butt4cak3** [comment]
Exactly. You would have to create a subdirectory in *code/* called *processing/* and put the source code there.

**Comment by johhnry** [comment]
Thanks, that's so cool !

Another question : I need a push access right? How do I get that?

**Comment by Butt4cak3** [comment]
You don't need push access. You have to create a "fork" of the repository. A fork is a complete copy of the original. Since that copy is your own, you can work in it. Once you're done, you can create a pull request, which is basically like saying "Look at my fork. I did all this cool stuff. Do you want to add it to the original project?". We can then look at the changes you added to your version of the project and copy them over to ours.

There's a bit more to it, but this is basically how things work. You make your own version of the Algorithm Archive, add code to it and we then copy it over to the official one.

If you want to learn more about this, there are lots of online resources. In addition to that, I'm currently working on a video series about how to contribute to the Algorithm Archive. I'll try to get the first few videos out this weekend.

If you have any more questions, don't hesitate to ask.

**Comment by johhnry** [comment]
Thanks for all your explanations, I'm currently seeing a tutorial on how to use Git.
I'll ask you if I have other questions.

Joseph

**Comment by johhnry** [comment]
I forked the repository but I don't know what is the next step.
Do I need to do this?

<img width="787" alt="capture" src="https://user-images.githubusercontent.com/35373357/42123437-61122068-7c52-11e8-8c69-744c51e46ca1.PNG">

**Comment by leios** [comment]
When you fork the repo, you will have your own version of the algorithm archive on your profile. You can clone that and make changes. When you push those changes to your own repo, you can then submit a pull request with those changes.

I would suggest putting all your changes onto a local branch first (which can be created with `git checkout -b BranchName`) and adding a second `remote` with `git remote add upstream git@github.com:algorithm-archivists/algorithm-archive.git`. By doing this, you can easily pull the latest changes from the master branch of the Algorithm Archive (`git pull upstream master`) and push your changes to your own branch (`git push origin BranchName`). Before pushing your changes to your own branch, I would pull the changes from `upstream` to be sure you are up to date and that your changes work with the current version of the Algorithm Archive.

You can create multiple branches with multiple changes, if you like and checkout the code on each branch with `git checkout BranchName`.

I hope that was clear. Let me know if you have further questions!

**Comment by johhnry** [comment]
Thanks it is quite clear for me :) .
I still don't understand what is a remote and this command : 
`git remote add upstream git@github.com:algorithm-archivists/algorithm-archive.git`

And the command : `git pull upstream master` creates an error :
 
```
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by leios** [comment]
A `remote` is a remote location where the code is held. There are two of these locations, your local one (usually called `origin`) and the Algorithm Archivists (here called `upstream`).

I think this error is because git doesn't know who you are and cannot authenticate you. Usually, this authentication happens via ssh (which you can set up by following something like this: https://help.github.com/articles/connecting-to-github-with-ssh/); however, ssh is not necessary. It might be easier for you to just use the https link instead.

So you have 2 options:
1. Remove your current `upstream` remote and add the https link instead:
```
git remote rm upstream
git remote add https://github.com/algorithm-archivists/algorithm-archive.git
```
2. Get ssh working via the [guide mentioned before](https://help.github.com/articles/connecting-to-github-with-ssh/)

The only real downside to using the https link is that you need to enter your github username and password each time. It's not a big deal for this, but most people prefer ssh for different reasons
