### ISSUE TITLE
Standardize on style

### ISSUE THREAD

**Issue by ubsan** [algorithm-archivists/algorithm-archive#18]

**Comment by leios** [comment]
Hey ubsan. This is a discussion we definitely need to have. I sent you a twitter message asking if you would join the discord channel discussion (if only for a brief bit) because we had a pretty lengthy discussion on this topic and your PR's. I guess I should have sent you an e-mail instead, sorry about that!

**Comment by leios** [comment]
But I guess it's fine to have the convo here. As far as style is concerned, I can only really speak to the languages I know (C / C++, Fortran, Julia, and Python). To me, readability is most important, but I also think the code should compile as-is (if possible). There will come a time when it is too difficult to do this, simply because the algorithms require too much code, but we can deal with that when the time comes.

Here's what makes code readable (to me):

1. **Comments**. I really like the comment block at the start of my files because it gives an indication of what the file is supposed to do and how it will do that along with basic compilation instructions. The simpler, the better. That said, I think having the same comment block at the start of every file does not make sense if the code is pasted at the end of the articles (as they currently are)
2. **Explicit typing whenever possible to avoid ambiguity**, also if choosing between types, choose the simpler type. Basically, if you are reading the code as an outsider to the language, it should make sense.
3. **Variable names should be simple and clear**. I don't care about the casing so much. This is super dependent on what people are used to and really doesn't matter for this.
4. **Little visual clutter**. If my eyes bug out when looking at the code, it is poorly written. 
5. **~"80-column rule"**. This one isn't so important, but because of how the code is displayed in text, it better look good in an editor with a relatively small width. In general, I feel that this helps keep the code more readable anyway, but that's up to debate. 

Because of the nature of the book, it's alright for people to have different styles, but the *cleanest* implementation will be accepted. When reading the code, I should never have to ask the following questions:
1. "What type this?"
2. "What is this variable?"
3. "What is the author trying to do?"

If these questions come up to the reader, there better be a comment nearby justifying why it is unclear. And if people submit versions of the code that are different, they should justify why their code is better and should be used instead of the code already present. 

I fully intend to have a `code/` directory in all the articles and want to make that change this week, but I haven't yet had the time. There's a lot of stuff I need to get done to account for all the contributors. We should hammer out a list of guidelines for contributers from here on so that we are clear.

Please let me know your thoughts. Algorithms are (mostly) language independent. The reader should be able grab an implementation in their favorite language, immediately understand it, and then play with it on their own to understand how it works.

**Comment by leios** [comment]
Alright, after a bit of internal discussion, I think the comment block is unnecessary in this case. Everyone knows the purpose of the code (because it's in the above article) and compile instructions are only really complicated if you want to avoid making makefiles. If we have a good chapter on all the different languages, then compilation should be straightforward.

Also: Comments in general should probably be used mainly to answer language-specific ambiguities. The rest of the questions should be answered in the accompanying article.

**Comment by ubsan** [comment]
So, as someone who writes a lot of C++, I'd like to base the style on these two things:

https://herbsutter.com/2013/08/12/gotw-94-solution-aaa-style-almost-always-auto/

https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md

The latter's formatting is not my favorite, but I think it's reasonable enough, and has support of the committee, and is, I think, a good base.

**Comment by ubsan** [comment]
Side note, on comments:

imo, the first thing in order of importance is *accessibility*. this means:

- single line comments are used, at most, for two lines

- block comments are a simple `/*` ... `*/` - there should be no other "comment markers"

this looks like:

```
// I'm a short comment
// I get dragged out to the next line
int foo();

/*
    I'm a long comment.
    boop ba doop
    balkjdafiosj
*/
int bar();
```

**Comment by ubsan** [comment]
Alright, we've agreed to use stroustrup style, with `auto` used rarely or not at all.

```c++
#include <iostream>
#include <cmath>

// Euclidean algorithm using modulus
int euclid_mod(int a, int b)
{
    a = std::abs(a);
    b = std::abs(b);
    while (b != 0) {
        auto temp = b;
        b = a%b;
        a = temp;
    }

    return a;
}

// Euclidean algorithm with subtraction
int euclid_sub(int a, int b)
{
    a = std::abs(a);
    b = std::abs(b);
    while (a != b) {
        if (a > b) {
            a -= b;
        }
        else {
            b -= a;
        }
    }

    return a;
}

int main()
{
    int check1 = euclid_mod(64*67, 64*81);
    int check2 = euclid_sub(128*12, 128*77);

    std::cout << check1 << '\n';
    std::cout << check2 << '\n';
}
```

**Comment by leios** [comment]
Yeah, I think there are times when `auto` makes sense, but should be used sparingly in this case. Thanks for the discussion. I'll mention this when writing the "how to contribute" section soon.

**Comment by Butt4cak3** [comment]
I'll just take the initiative and close this one. There hasn't been any activity for quite some time now and I think everything here has been resolved. If not, then feel free to reopen the issue or create a new one.
