### ISSUE TITLE
Convolution edge cases

### ISSUE THREAD

**Issue by VikingScientist** [algorithm-archivists/algorithm-archive#202]
Convolution is presented as an infinte sum over all indices, but for a finite input list this needs to be bounded. The question becomes what the function is assumed to be outside its definition range. The hand-written (Julia) code assumes the function to be zero outside its definition, while the FFT assumes it to be periodic. I'm pretty confident that the provided `conv`-function and `conv_fft` will give different output results, even if it is presented as they should produce the same. I say "pretty sure" because I had a hard time getting it to run and I am not a native Julia speaker.

**Comment by leios** [comment]
Ah yeah, I need to add images here. I had an old convolutions video that I took down that described this. This does provide different output, which is why the linear convolution is used primarily for filters, while the fft method is used for signal processing. This issue should stay up because I definitely need to re-write the section (and also talk about correlations). 

Thanks for bringing it back up to my attention!

**Comment by leios** [comment]
The convolution chapter has been largely revamped since this issue and I believe the issue has been properly addressed. Thanks again!
