### ISSUE TITLE
Journal of Open Source Education publication?

### ISSUE THREAD

**Issue by leios** [algorithm-archivists/algorithm-archive#373]
Hey, I have recently been made aware of a new journal, the [Journal of Open Source Education (JOSE)](http://jose.theoj.org/). It is similar to the [Journal of Open Source Software (JOSS)](https://joss.theoj.org/) in that the code, itself, is the publication. We simply need to provide a one-page intro to the project (which I should have no trouble writing on my own). I am considering publishing the Algorithm Archive in JOSE because it provides a citable reference so people can use the Algorithm Archive in their own projects.

To be clear: publishing the Algorithm Archive in JOSE does not restrict us from printing a version and publishing in that way later on. 

I am curious to hear what you guys think:

1. Is publishing in JOSE a good idea? Why or why not?
2. If we do publish in JOSE, how do we determine who is on the author list?
3. Are there better places to publish the AAA? Should we just wait for a physical copy?

The way I see it, the most up-to-date version of the AAA will always be online, so it makes sense to have a citable online reference. If we do decide to submit to JOSE, there is a lot I would like to do before-hand... so there is time to discuss.

**Comment by julianschacher** [comment]
I like the idea to get the AAA out there in a more official way.
Regarding the authors: You are obviously the main author, but in my opinion all contributors are authors as well, so I would include them.
The question is however, how this can be done, since the author list would be dynamic.
- Maybe stating you as the author and providing a link to the `CONTRIBUTORS.md` would be an option?
- If the document can be updated, putting the authors in the `.pdf` could also be done. I imagine that to maybe get quite messy / long tho, but it would give a more direct attribution / appreciation.

**Comment by leios** [comment]
Thanks for the tags.

We can probably publish with Schloss et. al. and explain the et. al. can be found int he CONTRIBUTORS.md file. I feel like the development team should also be considered primary authors, though, especially @julianschacher , @Butt4cak3 , @Gathros , etc.

**Comment by Amaras** [comment]
Since this was put on hold indefinitely, I'm closing it for now, feel free to reopen it later.
