### ISSUE TITLE
Adding people to the Algorithm Archivists organization

### ISSUE THREAD

**Issue by leios** [algorithm-archivists/algorithm-archive#376]
There are a few outstanding contributors I have been thinking about adding to the Algorithm Archivist organization. The organization, itself, has no special privileges, so I don't mind having quite a few people in the organization, but I am still hesitant to add people to the development team (with rights over the AAA).

My question here is how we should go about assigning new people to the organization. Should I just add people I trust or should we vote on each person individually? If we decide to vote, what is the best platform for the voting to occur?

The same goes for the development team. What do you guys think is the best way to become a member of the development team?

Should we restructure the organization?

**Comment by julianschacher** [comment]
I think, we could it do like the following:
- [1] People, who are active and contributed to the AAA, can be added to the organisation.
- [2a] If then after a longer period of time, the member is active (not necessarily on GitHub, but maybe on Discord and Twitch), the current Dev-Team decides upon adding the member to the Dev-Team.
- [2b] (maybe) If people are inactive for a long period of time on GitHub, Discord and Twitch just because of the lack of interest (and no other reason) (and aren't members of a team), they get removed from the organization again.

For the requirements, I would maybe suggest something like:
- [1] After a few contributions and/or long interaction on Discord and Twitch, the targeted person gets invited to the organization by Leios.
- [2a] After active 6 months - 1 year the addition of the member to the Dev-Team gets discussed.
- [2b] After inactivity for like a year (complete silence, reason=not interested) (and if it's not a team member), the person gets removed from the organization again.

**Comment by leios** [comment]
6 months seems like a long time. I figure 2 months should be sufficient

**Comment by julianschacher** [comment]
Yeah maybe. We just need to make sure, the future member is interested in the project and will be part of it for quite some time.

**Comment by leios** [comment]
Yeah, that's fair. When we finalize the "rules" here, they should also be written down somewhere.

**Comment by julianschacher** [comment]
The Wiki is probably a good place for that.

**Comment by leios** [comment]
I believe this issue can be closed. We currently discuss this on discord and update when necessary. There is also a question about it in the FAQ. This may be re-opened in the future if there is demand.

**Comment by julianschacher** [comment]
Yeah, I think we're fine with having a more personal and non-rule-based process for this at our current size. 
Also the link to the FAQ: https://github.com/algorithm-archivists/algorithm-archive/wiki/FAQ#how-do-i-join-the-algorithm-archivists-organization
