### ISSUE TITLE
How can we show good encapsulation and OOP practice?

### ISSUE THREAD

**Issue by PaddyKe** [algorithm-archivists/algorithm-archive#489]
In Pull request #438 (Gaussian elimination in Java) the discussion came up, how we can show good practice in terms of OOP and encapsulation, and which are the appropriate algorithms to use those techniques.

**Comment by Butt4cak3** [comment]
The goal of the AAA is not to show off good practice in certain languages. The main goal is to explain algorithms with text and code examples. If an algorithm calls for object oriented programming, then that will reflect in the code examples. Take a look at [Stable Marriage](https://www.algorithm-archive.org/contents/stable_marriage_problem/stable_marriage_problem.html), for example. The Java implementation utilizes a `Person` class with properly encapsulated data and so do all language implementations that support OOP.

The suggestion made in #438 is *not* a good example of encapsulation and good OOP practice and I know that the majority of the contributors of this project would agree with me. It's a hack around having to pass arguments to a method that only works because the example code's `main` method resides in the same static class as the method in question.

**Comment by Yordrar** [comment]
I already stated this in the PR #438, but I'll repeat it here just for the sake of discussion:
"it doesn't matter a lot having it as a variable or as a member of the class in terms of readability, i just want to have code in this project to be of the maximum quality possible (in my opinion at least, seeing that in this case some of you disagree with me) but if you guys think that it is fine as it is, so be it :)"

**Comment by Liikt** [comment]
In my opinion it actually does matter. A class member is there to describe a concrete instance of a class. As an example a circle can have multiple radii and thus be strictly different things. An algorithm on the other hand always (or mostly always depending on how much randomness you introduce) behave the same no matter the parameters. So they are indeed NOT different instances of the same class but the same instance just with different input. 

The only time I would put an algorithm into a class is in a task queue. But then it is a task and not an algorithm i want to abstract of.

Another reason I would disagree with you is that it leads to bad and/or to verbose code.
Take this as an example. 
```java
int x = Math.abs(num);
```
I hope you agree that that is the easiest and most understandable way of getting the absolute value of num.

According to your argument the code should look like following
```java
absClass abs = Math.abs(num);
int x = abs.invoke()
```
and that is very unnecessary in my opinion.

In general I agree with @Butt4cak3 that this is bad OOP style and just a hack around having to pass arguments, which isn't helping at all because you have to pass the arguments somewhere anyway. And if I have the choice between passing it to a constructor or to an algorithm directly my choice will be the algorithm in 99% of the cases.

**Comment by Yordrar** [comment]
Yeah i absolutely agree with you @Liikt, the code is better and more OOP without creating instances of a class that doesn't make sense to create, and yes, probably in a real application this code would be just a part of a function inside a class that does other things, absolutely, i was not referring to that in my review at all. the class methods are static, so you can access them without creating an object, and the methods can access the array when it is a member the same way as if it were an argument.

Now the thing that i think you guys are trying to convey is that the code is not usable or extensible if we put the array as a member of the class because if we want to change the array from other class we have to create an object or calling a "set" method or something similar, and that's absolutely correct, if we want code here to be copy&paste-friendly then we should do it like you guys say, my opinion only works for a proof of concept code that is by its own (which i thought we were going to put in the archive, but it seems not) so sorry for all the useless discussion, really

**Comment by Amaras** [comment]
Since the discussion hasn't officially resolved yet, can we get an official statement, or should I just close this issue?

**Comment by leios** [comment]
I think it's ok to close this issue. It ultimately amounts to better reviewing of OOP languages
