### ISSUE TITLE
Personal Issue List

### ISSUE THREAD

**Issue by ubsan** [algorithm-archivists/algorithm-archive#60]
- [x] tree_traversal: c++ - renamed to tree.cpp, fixed identifier style
- [x] tree_traveral: ocaml - added back
- [x] euclidean_algorithms: c++ - make sure it's good
- [x] euclidean_algorithms: all - rename the "euclidean_example" files to "euclidean"
- [x] convolutions: c++ - copy the fft from fft
- [x] convolutions: c++ - rewrite to make it compile
- [x] verlet: c++ - make sure it's good

- [x] sorting_searching: add C++

(gonna start fixing these once something similar to #61 is merged)

**Comment by Gathros** [comment]
#86 are you done, now @ubsan?

**Comment by julianschacherpp** [comment]
Maybe a better place for this To do list is a project?
Since we have the new organization now, people have the possibility to create projects. I did a project for C#, which isn't that loose however and targets a more strict tracking process.
But if you plan (@ubsan) this issue more as an ongoing issue list, a project may be a better place for that.

**Comment by ubsan** [comment]
ah, yeah, I've finished now.
