### ISSUE TITLE
Travis is down?

### ISSUE THREAD

**Issue by leios** [algorithm-archivists/algorithm-archive#764]
# Bug Report

Travis seems to not be checking any of the recent PRs. I'll look into this later this week

## For Algorithm Archive Developers

- [ ] The bug can be reproduced
- [ ] The bug can be fixed (if not, please explain why not in a comment below)
- [ ] There is a timeline to fix the bug
- [ ] The bug has been fixed (Please link the PR)

**Comment by leios** [comment]
I think this has been down since we merged the honkit PR, so we need to redo travis with the honkit commands. Is now a good time to maybe consider other CI strategies?

**Comment by berquist** [comment]
It's weird, because all the PRs are still building (https://travis-ci.org/github/algorithm-archivists/algorithm-archive/builds), but all my repositories have vanished from the left-hand side of https://travis-ci.org. Maybe they have finally made another step in the transition to https://travis-ci.com. I think the stuff you've been getting emails about to integrate with GH Actions will turn this back on. As the organization owner, did you get any emails about legacy Travis going away?

> Is now a good time to maybe consider other CI strategies?

Maybe. The advantage of Travis is that the YAML file is pretty simple and maintaining it isn't that difficult. All of the trouble we've had with it should tell you how complicated and annoying the other CI providers are. We should move to GitHub Actions CI, but if you aren't using one of their recipes, it will take some work to port.

**Comment by leios** [comment]
I believe this was fixed by switching to Github actions with #821
