### ISSUE TITLE
Segmentation fault on some of the asm-x64 examples

### ISSUE THREAD

**Issue by ShadowMitia** [algorithm-archivists/algorithm-archive#941]
# Bug Report

## Description

All of the asm-x64 examples seem to compile fine, at least with the `scons` system. But running gives segmentation faults on my machine.
The only ones that work for me:
- cooley_tukey
- monte_carlo_integration
- verlet_integration

All others have segmentation faults. Running `valgrind` seems to show it comes from `printf`, most likely a formatting issue of some sort.

### Steps to Reproduce

Clone the repositoy, and then run `scons -iQ`. Then you can run the individual executables in `build/asm-x64` and some of them will work and others won't.

### Expected behavior

All examples should run and output something and not seg fault.

## Environment
 - OS: Pop!_OS 21.10 x86_64
-  Kernel: 5.15.2-76051502-generic 
- CPU: AMD Ryzen 9 3900 (24) @ 3.100GHz

## Additional context

See #940 for more possible details and where the issue was detected.

## For Algorithm Archive Developers

- [ ] The bug can be reproduced
- [ ] The bug can be fixed (if not, please explain why not in a comment below)
- [ ] There is a timeline to fix the bug
- [ ] The bug has been fixed (Please link the PR)

**Comment by Amaras** [comment]
The output when I tried to run the files can be found [here](https://gist.github.com/Amaras/e830fd86baf2ee0febb88c1f9630b1fe)

In short, I can only reproduce the segfault in `forward_euler_method`.

Environment:
- OS: Ubuntu 20.04.3 x86_64
- Kernel : 5.4.0-89-generic
- CPU : Intel(R) Core(TM) i5-4210U CPU @ 1.70GHz

(Yeah, my computer is getting old...)

**Comment by stormofice** [comment]
As the code for the forward-euler-method chapter will probably not be reused after a rework of that chapter, it's probably not worth fixing this implementation.

However I did investigate a bit and the problem seems to be in line 65 were `mov rax, 1` should be `xor rax, rax`. While this does resolve the segfault it does not produce the correct solution and I kinda doubt that the implementation ever did.

I think this was the only faulty asm implementation, so this issue can be closed?

**Comment by leios** [comment]
Yeah, ok. Thanks a bunch for looking into this and sorry for the mix-up!
